"""Create tables

Revision ID: 18beed156422
Revises: b46a5e69124a
Create Date: 2023-09-07 15:06:10.619714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18beed156422'
down_revision = 'b46a5e69124a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
