"""creating tables

Revision ID: 551c4ede5ca6
Revises: 7ab02bd3ca72
Create Date: 2023-09-13 00:24:09.638677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551c4ede5ca6'
down_revision = '7ab02bd3ca72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
