"""creating tables

Revision ID: e816415d3c0c
Revises: 551c4ede5ca6
Create Date: 2023-09-13 18:08:53.396396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e816415d3c0c'
down_revision = '551c4ede5ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorytransactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_categorytransactions_category_id_categories')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_categorytransactions_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorytransactions'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_transactions_account_id_accounts'), 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_account_id_accounts'), type_='foreignkey')
        batch_op.drop_column('account_id')

    op.drop_table('categorytransactions')
    # ### end Alembic commands ###
